[versions]
aboutlibraries = "11.6.3"
androidx-activity = "1.10.1"
androidx-fragment = "1.8.6"
androidx-navigation = "2.8.9"
androidx-paging = "3.3.6"
appcenter = "5.0.6"
dagger = "2.56"
kotlin = "2.1.20"
okhttp = "4.12.0"
okio = "3.10.2"

[libraries]
aboutlibraries = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version = "0.37.2" }
adjust = { module = "com.adjust.sdk:adjust-android", version = "4.38.5" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.03.00" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.15.0" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "androidx-fragment" }
androidx-media = { module = "androidx.media:media", version = "1.7.0" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-work = { module = "androidx.work:work-runtime", version = "2.10.0" }
appcenter-distribute = { module = "com.microsoft.appcenter:appcenter-distribute", version.ref = "appcenter" }
appcenter-distribute-play = { module = "com.microsoft.appcenter:appcenter-distribute-play", version.ref = "appcenter" }
braze = { module = "com.braze:android-sdk-ui", version = "33.1.0" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "33.11.0" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
google-play-billing = { module = "com.android.billingclient:billing-ktx", version = "7.1.1" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-common" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version = "1.10.1" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.0" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
markwon = { module = "io.noties.markwon:core", version = "4.6.2" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
plugin-aboutlibraries = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutlibraries" }
plugin-android = { module = "com.android.tools.build:gradle", version = "8.9.0" }
plugin-androidx-navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
plugin-dagger = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version = "1.13.0" }
plugin-sentry = { module = "io.sentry:sentry-android-gradle-plugin", version = "5.3.0" }
plugin-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.52.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.14.1" }
sentry = { module = "io.sentry:sentry-android" }
sentry-bom = { module = "io.sentry:sentry-bom", version = "8.5.0" }
sentry-okhttp = { module = "io.sentry:sentry-okhttp" }
snowplow-android-tracker = { module = "com.snowplowanalytics:snowplow-android-tracker", version = "6.2.0" }
turbine = { module = "app.cash.turbine:turbine", version = "1.2.0" }
